// clienteDemo/src/app/cart/current.cart.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Router } from '@angular/router';
import { JsonPipe } from '@angular/common';
import { AuthService, Usuario } from '../auth/auth.service';
import { IErrorController } from '../tools/error.handler';
import * as errorHanlder from '../tools/error.handler';
import { Cart, CartService, ICartArticleValidation } from './cart.service';

@Component({
    selector: 'app-current-cart',
    templateUrl: './current.cart.component.html'
})
export class CurrentCartComponent implements errorHanlder.IErrorController, OnInit {
    errorMessage: string;
    errors: Map<string, string>;

    validation: ICartArticleValidation;

    @Input()
    currentCart: Cart;

    constructor(private cartService: CartService, private router: Router) { }

    ngOnInit(): void {
        this.refresh();
    }

    refresh() {
        this.cartService.getCurrentCart()
            .then(result => this.currentCart = result)
            .catch(error => errorHanlder.procesarValidacionesRest(this, error));
    }

    checkout() {
        this.cartService.checkout()
            .then(_ => this.refresh())
            .catch(error => errorHanlder.procesarValidacionesRest(this, error));
    }

    validate() {
        this.cartService.validate()
            .then(validation => this.validation = validation)
            .catch(error => errorHanlder.procesarValidacionesRest(this, error));
    }

}

<h2>Carrito Actual</h2>

<form *ngIf="currentCart">
    <mat-form-field>
        <input matInput placeholder="Id" [value]="currentCart._id" readonly>
    </mat-form-field>

    <mat-form-field>
        <input matInput placeholder="Usuario" [value]="currentCart.userId" readonly>
    </mat-form-field>


    <table mat-table [dataSource]="currentCart.articles" class="mat-elevation-z8">
        <ng-container matColumnDef="id">
            <th mat-header-cell *matHeaderCellDef> Id </th>
            <td mat-cell *matCellDef="let element"> {{element.articleId}} </td>
        </ng-container>

        <ng-container matColumnDef="quantity">
            <th mat-header-cell *matHeaderCellDef> Cantidad </th>
            <td mat-cell *matCellDef="let element"> {{element.quantity}} </td>
        </ng-container>

        <tr mat-header-row *matHeaderRowDef="['id', 'quantity']"></tr>
        <tr mat-row *matRowDef="let row; columns: ['id', 'quantity'];"></tr>
    </table>

    <BR>
    <div>
        <div *ngIf="errorMessage">{{errorMessage}}</div>
        <button mat-button color="primary" (click)="validate()">Validar</button>
        <button mat-button color="primary" (click)="checkout()">Checkout</button>
        <button mat-button color="primary" (click)="refresh()">Refresh</button>
        <button mat-button color="disabled" [routerLink]="['/']">Cancelar</button>
    </div>
</form>

{{validation | json}}

<div *ngIf="errorMessage">{{errorMessage}}</div>

// api_client_react/src/cart/CurrentCart.tsx
import React from "react";
import CommonComponent, { ICommonProps } from "../system/tools/CommonComponent";
import { checkout, getCurrentCart, ICart, ICartValidation, validate } from "./CartApi";

interface IState {
    currentCart?: ICart;
    validation?: ICartValidation;
}

export default class CurrentCart extends CommonComponent<ICommonProps, IState> {
    constructor(props: ICommonProps) {
        super(props);

        this.state = {};

        this.loadCurrentCart();
    }

    public loadCurrentCart = async () => {
        try {
            const result = await getCurrentCart();
            this.setState({
                currentCart: result,
            });
        } catch (error) {
            this.processRestValidations(error);
        }
    }

    public refresh = () => {
        this.loadCurrentCart();
    }

    public validate = async () => {
        try {
            const result = await validate();
            this.setState({
                validation: result,
            });
        } catch (error) {
            this.processRestValidations(error);
        }
    }

    public checkout = async () => {
        try {
            await checkout();
            this.loadCurrentCart();
        } catch (error) {
            this.processRestValidations(error);
        }
    }

    public render() {
        const cart = this.state.currentCart;
        return (
            <div className="global_content">
                <h2 className="global_title">Carrito Actual</h2>

                <div hidden={!cart}>
                    <div className="form-group">
                        <label>Id Carrito</label>
                        <input className="form-control" id="cartId" value={cart ? cart._id : ""} disabled />
                    </div>

                    <div className="form-group">
                        <label>Id Usuario</label>
                        <input className="form-control" id="userId" value={cart ? cart.userId : ""} disabled />
                    </div>

                    <table id="articles" className="table">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Cantidad</th>
                                <th>Validado</th>
                            </tr>
                        </thead>
                        <tbody>
                            {(cart && cart.articles) ?
                                cart.articles!.map((article, i) => {
                                    return (
                                        <tr key={i}>
                                            <td>{article.articleId}</td>
                                            <td>{article.quantity}</td>
                                            <td>{article.validated}</td>
                                        </tr>
                                    );

                                }) : null
                            }
                        </tbody>
                    </table>

                    <div className="btn-group ">
                        <button className="btn btn-primary" onClick={this.validate} >Validar</button >
                        <button className="btn btn-primary" onClick={this.checkout} >Check out</button >
                        <button className="btn btn-primary" onClick={this.refresh} >Refresh</button >
                        <button className="btn btn-light" onClick={this.goHome} >Cancelar</button >
                    </div >
                </div>

                <div className="form-group" hidden={!this.state.validation}>
                    <br/>
                    <label>Token</label>
                    <input className="form-control"
                        id="validation"
                        value={JSON.stringify(this.state.validation)}
                        disabled
                    />
                </div>

                <div hidden={!this.errorMessage}
                    className="alert alert-danger"
                    role="alert">
                    {this.errorMessage}
                </div>
            </div>
        );
    }
}
