// api_client_angular/src/app/cart/current.cart.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Cart, CartService, ICartValidation } from './cart.service';
import { BasicFromGroupController } from '../tools/error.form';

@Component({
    selector: 'app-current-cart',
    templateUrl: './current.cart.component.html'
})
export class CurrentCartComponent extends BasicFromGroupController implements OnInit {
    validation: ICartValidation;

    @Input()
    currentCart: Cart;

    constructor(private cartService: CartService, private router: Router) {
        super();
    }

    ngOnInit(): void {
        this.refresh();
    }

    refresh() {
        this.cartService.getCurrentCart()
            .then(result => this.currentCart = result)
            .catch(error => this.processRestValidations(error));
    }

    checkout() {
        this.cartService.checkout()
            .then(_ => this.refresh())
            .catch(error => this.processRestValidations(error));
    }

    validate() {
        this.cartService.validate()
            .then(validation => this.validation = validation)
            .catch(error => this.processRestValidations(error));
    }

}

<h2>Carrito Actual</h2>

<form *ngIf="currentCart">
    <div class="form-group form-inline">
        <label for="_id" class="mr-sm-2" >Id Carrito</label>
        <input class="form-control form-control-sm" id="_id" [value]="currentCart._id" readonly>
    </div>

    <div class="form-group form-inline mr-sm-2">
        <label for="userId" class="mr-sm-2" >Id Usuario</label>
        <input class="form-control form-control-sm" id="userId" [value]="currentCart.userId" readonly>
    </div>

    <div class="form-group">
        <label for="articles">Artículos</label>

        <table id="articles" class="table">

            <head>
                <tr>
                    <th> Id </th>
                    <th> Cantidad </th>
                    <th> Validado </th>
                </tr>
            </head>
            <tbody>
                <tr *ngFor="let element of currentCart.articles">
                    <td> {{element.articleId}} </td>
                    <td> {{element.quantity}} </td>
                    <td> {{element.validated}} </td>
                </tr>
            </tbody>
        </table>

        <div class="btn-group ">
            <div *ngIf="errorMessage">{{errorMessage}}</div>
            <button class="btn btn-primary " (click)="validate()">Validar</button>
            <button class="btn btn-primary " (click)="checkout()">Checkout</button>
            <button class="btn btn-primary " (click)="refresh()">Refresh</button>
            <button class="btn btn-light " [routerLink]="['/']">Cancelar</button>
        </div>
    </div>
</form>

{{validation | json}}

<div *ngIf="errorMessage">{{errorMessage}}</div>

// api_client_react/src/cart/CurrentCart.tsx
import React from "react";
import CommonComponent, { ICommonProps } from "../system/tools/CommonComponent";
import { checkout, getCurrentCart, ICart, ICartValidation, validate } from "./CartApi";

interface IState {
    currentCart?: ICart;
    validation?: ICartValidation;
}

export default class CurrentCart extends CommonComponent<ICommonProps, IState> {
    constructor(props: ICommonProps) {
        super(props);

        this.state = {};

        this.loadCurrentCart();
    }

    public loadCurrentCart = async () => {
        try {
            const result = await getCurrentCart();
            this.setState({
                currentCart: result,
            });
        } catch (error) {
            this.processRestValidations(error);
        }
    }

    public refresh = () => {
        this.loadCurrentCart();
    }

    public validate = async () => {
        try {
            const result = await validate();
            this.setState({
                validation: result,
            });
        } catch (error) {
            this.processRestValidations(error);
        }
    }

    public checkout = async () => {
        try {
            await checkout();
            this.loadCurrentCart();
        } catch (error) {
            this.processRestValidations(error);
        }
    }

    public render() {
        const cart = this.state.currentCart;
        return (
            <div className="global_content">
                <h2 className="global_title">Carrito Actual</h2>

                <div hidden={!cart}>
                    <div className="form-group">
                        <label>Id Carrito</label>
                        <input className="form-control" id="cartId" value={cart ? cart._id : ""} disabled />
                    </div>

                    <div className="form-group">
                        <label>Id Usuario</label>
                        <input className="form-control" id="userId" value={cart ? cart.userId : ""} disabled />
                    </div>

                    <table id="articles" className="table">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Cantidad</th>
                                <th>Validado</th>
                            </tr>
                        </thead>
                        <tbody>
                            {(cart && cart.articles) ?
                                cart.articles!.map((article, i) => {
                                    return (
                                        <tr key={i}>
                                            <td>{article.articleId}</td>
                                            <td>{article.quantity}</td>
                                            <td>{article.validated}</td>
                                        </tr>
                                    );

                                }) : null
                            }
                        </tbody>
                    </table>

                    <div className="btn-group ">
                        <button className="btn btn-primary" onClick={this.validate} >Validar</button >
                        <button className="btn btn-primary" onClick={this.checkout} >Check out</button >
                        <button className="btn btn-primary" onClick={this.refresh} >Refresh</button >
                        <button className="btn btn-light" onClick={this.goHome} >Cancelar</button >
                    </div >
                </div>

                <div className="form-group" hidden={!this.state.validation}>
                    <br/>
                    <label>Token</label>
                    <input className="form-control"
                        id="validation"
                        value={JSON.stringify(this.state.validation)}
                        disabled
                    />
                </div>

                <div hidden={!this.errorMessage}
                    className="alert alert-danger"
                    role="alert">
                    {this.errorMessage}
                </div>
            </div>
        );
    }
}
