// api_client_angular/src/app/orders/order.detail.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { BasicFromGroupController } from '../tools/error.form';
import { Order, OrderService } from './order.service';

@Component({
    selector: 'app-order-detail',
    templateUrl: './order.detail.component.html'
})
export class OrderDetailComponent extends BasicFromGroupController implements OnInit {
    form = new FormGroup({
        orderId: new FormControl('', [Validators.required]),
        method: new FormControl('', [Validators.required]),
        amount: new FormControl('', [Validators.required]),
    });

    payment = false;
    order: Order;

    constructor(private orderService: OrderService, private route: ActivatedRoute) {
        super();
    }

    ngOnInit(): void {
        this.payment = false;
        this.route.params.subscribe(params => {
            this.form.get('orderId').setValue(params['id']);
            this.submitForm();
        });
    }

    submitForm() {
        this.payment = false;
        if (this.form.get('orderId').value) {
            this.orderService.getOrder(this.form.get('orderId').value)
                .then(order => this.order = order)
                .catch(err => this.processRestValidations(err));
        }
    }

    addPayment() {
        this.payment = true;
    }

    paymentSubmit() {
        if (this.form.get('orderId').value) {
            this.orderService
                .addPayment(
                    this.form.get('orderId').value,
                    this.form.get('method').value,
                    this.form.get('amount').value)
                .then(order => this.submitForm())
                .catch(err => this.processRestValidations(err));
        }
    }
}

<h2>Detalle de Orden</h2>

<form [formGroup]="form">
    <div class="form-group">
        <label for="orderId">Order Id</label>
        <input class="form-control" [class.is-invalid]="hasError('orderId')" id="orderId" formControlName="orderId">
        <div *ngIf="hasError('orderId')" class="invalid-feedback">{{getErrorText('orderId')}}</div>
    </div>

    <div *ngIf="errorMessage" class="invalid-feedback">{{errorMessage}}</div>

    <div class="btn-group ">
        <button class="btn btn-primary " (click)="submitForm() ">Buscar</button>
        <button class="btn btn-light " [routerLink]="[ '/'] ">Cancelar</button>
    </div>
</form>
<br>

<form *ngIf="order">
    <div class="form-group form-inline">
        <h4>Detalle de Orden : {{order.id}}</h4>
    </div>

    <div class="form-group form-inline">
        <label for="cartId" class="mr-sm-2">Cart Id</label>
        <input class="form-control form-control-sm" id="cartId" [value]="order.cartId" readonly>
    </div>

    <div class="form-group form-inline">
        <label for="status" class="mr-sm-2">Estado</label>
        <input class="form-control form-control-sm" id="status" [value]="order.status" readonly>
    </div>

    <div class="form-group form-inline">
        <label for="totalPrice" class="mr-sm-2">Importe Total</label>
        <input class="form-control form-control-sm" id="totalPrice" [value]="order.totalPrice" readonly>
    </div>

    <div class="form-group form-inline">
        <label for="totalPayment" class="mr-sm-2">Pago Total</label>
        <input class="form-control form-control-sm" id="totalPayment" [value]="order.totalPayment" readonly>
    </div>

    <div class="form-group form-inline">
        <label for="created" class="mr-sm-2">Creada</label>
        <input class="form-control form-control-sm" id="created" [value]="order.created" readonly>
    </div>

    <div class="form-group form-inline">
        <label for="updated" class="mr-sm-2">Actualizada</label>
        <input class="form-control form-control-sm" id="updated" [value]="order.updated" readonly>
    </div>

    <BR>
    <h4>Artículos</h4>
    <table>
        <thead>
            <tr>
                <th> Id </th>
                <th> Cantidad </th>
                <th> Precio Unit. </th>
                <th> Valido </th>
                <th> Validado </th>
            </tr>
        </thead>

        <tbody>
            <tr *ngFor="let element of order.articles">
                <td> {{element.id}} </td>
                <td> {{element.quantity}} </td>
                <td> {{element.unitaryPrice}} </td>
                <td> {{element.valid}} </td>
                <td> {{element.validated}} </td>
            </tr>
        </tbody>
    </table>

    <BR>
    <h4>Pagos</h4>
    <table>
        <thead>
            <tr>
                <th> Método </th>
                <th> Import </th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let element of order.payment">
                <td> {{element.method}} </td>
                <td> {{element.amount}} </td>
            </tr>
        </tbody>
    </table>

    <BR>
    <div class="btn-group ">
        <div *ngIf="errorMessage">{{errorMessage}}</div>
        <button class="btn btn-primary " (click)="addPayment()">Agregar Pago</button>
        <button class="btn btn-primary " (click)="submitForm()">Actualizar</button>
        <button class="btn btn-light " [routerLink]="['/']">Cancelar</button>
    </div>
</form>
<BR>

<form [formGroup]="form" *ngIf="payment">
    <div class="form-group form-inline">
        <h4>Agregar Pago</h4>
    </div>

    <div class="form-group">
        <label for="method">Método</label>
        <input class="form-control" [class.is-invalid]="hasError('method')" id="method" formControlName="method">
        <div *ngIf="hasError('method')" class="invalid-feedback">{{getErrorText('method')}}</div>
    </div>

    <div class="form-group">
        <label for="amount">Importe</label>
        <input class="form-control" [class.is-invalid]="hasError('amount')" id="amount" formControlName="amount">
        <div *ngIf="hasError('amount')" class="invalid-feedback">{{getErrorText('amount')}}</div>
    </div>

    <div *ngIf="errorMessage" class="invalid-feedback">{{errorMessage}}</div>

    <div class="btn-group ">
        <button class="btn btn-primary " (click)="paymentSubmit() ">Agregar</button>
        <button class="btn btn-light " [routerLink]="[ '/'] ">Cancelar</button>
    </div>
</form>

// api_client_react/src/orders/OrderDetail.tsx
import React from "react";
import CommonComponent, { ICommonProps } from "../system/tools/CommonComponent";
import AddPayment from "./AddPayment";
import { getOrder, IOrder, IPayment } from "./OrdersApi";

interface IState {
    order?: IOrder;
    payment?: IPayment;
}

interface IOrderDetailProps extends ICommonProps {
    orderId: string;
}

export default class OrderDetail extends CommonComponent<IOrderDetailProps, IState> {
    constructor(props: IOrderDetailProps) {
        super(props);

        this.state = {};

        this.loadOrder();
    }

    public cancelPayment = () => {
        this.setState({ payment: undefined });
        this.loadOrder();
    }

    public loadOrder = async () => {
        try {
            const order = await getOrder(this.props.orderId);
            this.setState({ order });
        } catch (error) {
            this.processRestValidations(error);
        }
    }

    public addPayment = () => {
        try {
            this.setState(
                {
                    payment: {
                        amount: 0,
                        method: "",
                    },
                });
        } catch (error) {
            this.processRestValidations(error);
        }
    }

    public render() {
        const order = this.state.order;
        return order ? (
            <div className="global_content">
                <h2 className="global_title">Detalle de Orden : {order.id}</h2>

                <div>
                    <div className="form-group">
                        <label>Cart Id</label>
                        <input value={order.cartId} disabled />
                    </div>
                    <div className="form-group">
                        <label>Estado</label>
                        <input value={order.status} disabled />
                    </div>
                    <div className="form-group">
                        <label>Importe Total</label>
                        <input value={order.totalPrice} disabled />
                    </div>
                    <div className="form-group">
                        <label>Pago Total</label>
                        <input value={order.totalPayment} disabled />
                    </div>
                    <div className="form-group">
                        <label>Creada</label>
                        <input value={order.created} disabled />
                    </div>
                    <div className="form-group">
                        <label>Actualizada</label>
                        <input value={order.updated} disabled />
                    </div>
                </div>

                <table id="articles" className="table">
                    <thead>
                        <tr>
                            <th> Id </th>
                            <th> Cantidad </th>
                            <th> Precio Unit. </th>
                            <th> Valido </th>
                            <th> Validado </th>
                        </tr>
                    </thead>
                    <tbody>
                        {(order && order.articles) ?
                            order.articles!.map((article, i) => {
                                return (
                                    <tr key={i}>
                                        <td>{article.id}</td>
                                        <td>{article.quantity}</td>
                                        <td>{article.unitaryPrice}</td>
                                        <td>{article.valid}</td>
                                        <td>{article.validated}</td>
                                    </tr>
                                );

                            }) : null
                        }
                    </tbody>
                </table>

                <br />
                <h4>Pagos</h4>
                <table>
                    <thead>
                        <tr>
                            <th> Método </th>
                            <th> Import </th>
                        </tr>
                    </thead>
                    <tbody>
                        {(order && order.payment) ?
                            order.payment!.map((pay, i) => {
                                return (
                                    <tr key={i}>
                                        <td>{pay.method}</td>
                                        <td>{pay.amount}</td>
                                    </tr>
                                );
                            }) : null
                        }
                    </tbody>
                </table>

                <br />
                <div className="btn-group ">
                    <button className="btn btn-primary" onClick={this.addPayment} >Agregar Pago</button >
                    <button className="btn btn-primary" onClick={this.loadOrder} >Actualizar</button >
                </div >
                <br />
                {(this.state.payment) ?
                    <AddPayment
                        orderId={this.state.order!.id}
                        payment={this.state.payment!}
                        onPaymentAdded={this.cancelPayment} />
                    : ""
                }
            </div>
        ) : "";
    }
}
