// apiClient/src/app/orders/order.detail.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import * as errorHandler from '../tools/error.handler';
import { Order, OrderService } from './order.service';

@Component({
    selector: 'app-order-detail',
    templateUrl: './order.detail.component.html'
})
export class OrderDetailComponent implements errorHandler.IErrorController, OnInit {
    errorMessage: string;
    errors = new Map();

    orderId = new FormControl('', [Validators.required]);
    method = new FormControl('', [Validators.required]);
    amount = new FormControl('', [Validators.required]);

    payment = false;
    order: Order;

    constructor(private orderService: OrderService, private router: Router, private route: ActivatedRoute) { }

    ngOnInit(): void {
        this.payment = false;
        this.route.params.subscribe(params => {
            this.orderId.setValue(params['id']);
            this.submitForm();
        });
    }

    submitForm() {
        this.payment = false;
        if (this.orderId.value) {
            this.orderService.getOrder(this.orderId.value)
                .then(order => this.order = order)
                .catch(err => errorHandler.processRestValidations(this, err));
        }
    }

    addPayment() {
        this.payment = true;
    }

    paymentSubmit() {
        if (this.orderId.value) {
            this.orderService.addPayment(this.orderId.value, this.method.value, this.amount.value)
                .then(order => this.submitForm())
                .catch(err => errorHandler.processRestValidations(this, err));
        }
    }

}

<h2>Detalle de Orden</h2>

<form #f="ngForm" novalidate>
    <mat-form-field>
        <input matInput placeholder="Order Id" [formControl]="orderId" />

        <mat-error *ngIf="orderId?.invalid">
            {{ errors.get('orderId') ? errors.get('orderId') : "Valor no válido." }}
        </mat-error>
    </mat-form-field>
    <div>
        <mat-error *ngIf="errorMessage">
            {{errorMessage}}
            <BR>
        </mat-error>
        <button mat-button color="primary" (click)="submitForm()">Buscar</button>
        <button mat-button color="disabled" [routerLink]="['/']">Cerrar</button>
    </div>
    <BR>
</form>

<form *ngIf="order">
    <mat-form-field>
        <input matInput placeholder="Id" [value]="order.id" readonly>
    </mat-form-field>

    <mat-form-field>
        <input matInput placeholder="Cart Id" [value]="order.cartId" readonly>
    </mat-form-field>

    <mat-form-field>
        <input matInput placeholder="Estado" [value]="order.status" readonly>
    </mat-form-field>

    <mat-form-field>
        <input matInput placeholder="Importe Total" [value]="order.totalPrice" readonly>
    </mat-form-field>

    <mat-form-field>
        <input matInput placeholder="Creada" [value]="order.created" readonly>
    </mat-form-field>

    <mat-form-field>
        <input matInput placeholder="Actualizada" [value]="order.updated" readonly>
    </mat-form-field>

    <table mat-table [dataSource]="order.articles" class="mat-elevation-z8">
        <ng-container matColumnDef="id">
            <th mat-header-cell *matHeaderCellDef> Id </th>
            <td mat-cell *matCellDef="let element"> {{element.id}} </td>
        </ng-container>

        <ng-container matColumnDef="quantity">
            <th mat-header-cell *matHeaderCellDef> Cantidad </th>
            <td mat-cell *matCellDef="let element"> {{element.quantity}} </td>
        </ng-container>

        <ng-container matColumnDef="unitaryPrice">
            <th mat-header-cell *matHeaderCellDef> Precio Unit. </th>
            <td mat-cell *matCellDef="let element"> {{element.unitaryPrice}} </td>
        </ng-container>

        <ng-container matColumnDef="valid">
            <th mat-header-cell *matHeaderCellDef> Valido </th>
            <td mat-cell *matCellDef="let element"> {{element.valid}} </td>
        </ng-container>

        <ng-container matColumnDef="validated">
            <th mat-header-cell *matHeaderCellDef> Validado </th>
            <td mat-cell *matCellDef="let element"> {{element.validated}} </td>
        </ng-container>

        <tr mat-header-row *matHeaderRowDef="['id', 'quantity', 'unitaryPrice', 'valid', 'validated']"></tr>
        <tr mat-row *matRowDef="let row; columns: ['id', 'quantity', 'unitaryPrice', 'valid', 'validated'];"></tr>
    </table>

    <BR>
    <div>
        <div *ngIf="errorMessage">{{errorMessage}}</div>
        <button mat-button color="primary" (click)="submitForm()">Actualizar</button>
        <button mat-button color="disabled" [routerLink]="['/']">Cancelar</button>
    </div>
</form>

<div *ngIf="errorMessage">{{errorMessage}}</div>

// api_client_react/src/orders/OrderDetail.tsx
import React from "react";
import CommonComponent, { ICommonProps } from "../system/tools/CommonComponent";
import AddPayment from "./AddPayment";
import { getOrder, IOrder, IPayment } from "./OrdersApi";

interface IState {
    order?: IOrder;
    payment?: IPayment;
}

interface IOrderDetailProps extends ICommonProps {
    orderId: string;
}

export default class OrderDetail extends CommonComponent<IOrderDetailProps, IState> {
    constructor(props: IOrderDetailProps) {
        super(props);

        this.state = {};

        this.loadOrder();
    }

    public cancelPayment = () => {
        this.setState({ payment: undefined });
        this.loadOrder();
    }

    public loadOrder = async () => {
        try {
            const order = await getOrder(this.props.orderId);
            this.setState({ order });
        } catch (error) {
            this.processRestValidations(error);
        }
    }

    public addPayment = () => {
        try {
            this.setState(
                {
                    payment: {
                        amount: 0,
                        method: "",
                    },
                });
        } catch (error) {
            this.processRestValidations(error);
        }
    }

    public render() {
        const order = this.state.order;
        return order ? (
            <div className="global_content">
                <h2 className="global_title">Detalle de Orden : {order.id}</h2>

                <div>
                    <div className="form-group">
                        <label>Cart Id</label>
                        <input value={order.cartId} disabled />
                    </div>
                    <div className="form-group">
                        <label>Estado</label>
                        <input value={order.status} disabled />
                    </div>
                    <div className="form-group">
                        <label>Importe Total</label>
                        <input value={order.totalPrice} disabled />
                    </div>
                    <div className="form-group">
                        <label>Pago Total</label>
                        <input value={order.totalPayment} disabled />
                    </div>
                    <div className="form-group">
                        <label>Creada</label>
                        <input value={order.created} disabled />
                    </div>
                    <div className="form-group">
                        <label>Actualizada</label>
                        <input value={order.updated} disabled />
                    </div>
                </div>

                <table id="articles" className="table">
                    <thead>
                        <tr>
                            <th> Id </th>
                            <th> Cantidad </th>
                            <th> Precio Unit. </th>
                            <th> Valido </th>
                            <th> Validado </th>
                        </tr>
                    </thead>
                    <tbody>
                        {(order && order.articles) ?
                            order.articles!.map((article, i) => {
                                return (
                                    <tr key={i}>
                                        <td>{article.id}</td>
                                        <td>{article.quantity}</td>
                                        <td>{article.unitaryPrice}</td>
                                        <td>{article.valid}</td>
                                        <td>{article.validated}</td>
                                    </tr>
                                );

                            }) : null
                        }
                    </tbody>
                </table>

                <br />
                <h4>Pagos</h4>
                <table>
                    <thead>
                        <tr>
                            <th> Método </th>
                            <th> Import </th>
                        </tr>
                    </thead>
                    <tbody>
                        {(order && order.payment) ?
                            order.payment!.map((pay, i) => {
                                return (
                                    <tr key={i}>
                                        <td>{pay.method}</td>
                                        <td>{pay.amount}</td>
                                    </tr>
                                );
                            }) : null
                        }
                    </tbody>
                </table>

                <br />
                <div className="btn-group ">
                    <button className="btn btn-primary" onClick={this.addPayment} >Agregar Pago</button >
                    <button className="btn btn-primary" onClick={this.loadOrder} >Actualizar</button >
                </div >
                <br />
                {(this.state.payment) ?
                    <AddPayment
                        orderId={this.state.order!.id}
                        payment={this.state.payment!}
                        onPaymentAdded={this.cancelPayment} />
                    : ""
                }
            </div>
        ) : "";
    }
}
