// api_client_react/src/users/Login.tsx
import React from "react";
import "../styles.css";
import { login } from "../system/store/SessionStore";
import CommonComponent, { ICommonProps } from "../system/tools/CommonComponent";
import ErrorLabel from "../system/tools/ErrorLabel";

interface IState {
    login: string;
    password: string;
}

export default class Login extends CommonComponent<ICommonProps, IState> {
    constructor(props: ICommonProps) {
        super(props);

        this.state = {
            login: "",
            password: "",
        };
    }

    public loginClick = async () => {
        this.cleanRestValidations();
        if (!this.state.login) {
            this.addError("login", "No puede estar vacío");
        }
        if (!this.state.password) {
            this.addError("password", "No puede estar vacío");
        }

        if (this.hasErrors()) {
            this.forceUpdate();
            return;
        }

        try {
            await login(this.state);
            this.props.history.push("/");
        } catch (error) {
            this.processRestValidations(error);
        }
    }

    public render() {
        return (
            <div className="global_content">
                <h2 className="global_title">Login</h2>

                <form onSubmit={(e) => e.preventDefault()}>
                    <div className="form-group">
                        <label>Usuario</label>
                        <input id="login" type="text"
                            onChange={this.updateState}
                            className={this.getErrorClass("login", "form-control")}>
                        </input>
                        <ErrorLabel error={this.getErrorText("login")} />
                    </div>

                    <div className="form-group">
                        <label>Password</label>
                        <input id="password" type="password"
                            onChange={this.updateState}
                            className={this.getErrorClass("password", "form-control")}>
                        </input>
                        <ErrorLabel error={this.getErrorText("password")} />
                    </div>

                    <div hidden={!this.errorMessage}
                        className="alert alert-danger"
                        role="alert">
                        {this.errorMessage}
                    </div>

                    <div className="btn-group ">
                        <button className="btn btn-primary" onClick={this.loginClick}>Login</button>
                        <button className="btn btn-light" onClick={this.goHome} >Cancelar</button >
                    </div >
                </form >
            </div >
        );
    }
}

// api_client_angular/src/app/auth/login.component.ts
import { Component } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../auth/auth.service';
import { BasicFromGroupController } from '../tools/error.form';

@Component({
    selector: 'app-auth-login',
    templateUrl: './login.component.html'
})
export class LoginComponent extends BasicFromGroupController {
    form = new FormGroup({
        login: new FormControl('', [Validators.required]),
        password: new FormControl('', [Validators.required]),
    });

    constructor(private authService: AuthService, private router: Router) {
        super();
     }

    submitForm() {
        this.cleanRestValidations();

        this.authService
            .login(this.form.get('login').value, this.form.get('password').value)
            .then(principal => {
                this.router.navigate(['/']);
            })
            .catch(error => this.processRestValidations(error));
    }
}

<h2>Login</h2>

<form [formGroup]="form">
    <div class="form-group">
        <label for="login">Usuario</label>
        <input class="form-control" [class.is-invalid]="hasError('login')" id="login" formControlName="login">
        <div *ngIf="hasError('login')" class="invalid-feedback">{{getErrorText('login')}}</div>
    </div>

    <div class="form-group">
        <label for="password">Password</label>
        <input class="form-control" [class.is-invalid]="hasError('password')" id="password" formControlName="password" type="password">
        <div *ngIf="hasError('password')" class="invalid-feedback">{{getErrorText('password')}}</div>
    </div>

    <div *ngIf="errorMessage" class="invalid-feedback">{{errorMessage}}</div>

    <div class="btn-group ">
        <button class="btn btn-primary " (click)="submitForm() " [disabled]="form.invalid ">Login</button>
        <button class="btn btn-light " [routerLink]="[ '/'] ">Cancelar</button>
    </div>
</form>
